name: Contributors

on:
  push:
    branches:
      - master

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: |
          yarn
      - name: Build
        run: |
          yarn build

      - uses: ./
        name: contributors-rounded-avatar
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          repo: antvis/g2
          svgPath: examples/contributors-rounded-avatar.svg
          round: true
          includeBots: true
